/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAssignmentForUserWithHintsResponse } from "./dailyAssignmentForUserWithHintsResponse";
import type { AssignmentWithHintsReportResponseReport } from "./assignmentWithHintsReportResponseReport";

export interface AssignmentWithHintsReportResponse {
	assignment: DailyAssignmentForUserWithHintsResponse;
	report?: AssignmentWithHintsReportResponseReport;
}
