/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */

export type AssignmentStatus = (typeof AssignmentStatus)[keyof typeof AssignmentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignmentStatus = {
	not_started: "not_started",
	in_progress: "in_progress",
	partially_completed: "partially_completed",
	completed: "completed",
	not_completed: "not_completed",
	expired: "expired",
} as const;
