/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateReportMessage } from "./createReportMessage";
import type { CreateReportMediaLinks } from "./createReportMediaLinks";

export interface CreateReport {
	daily_assignment_id: number;
	user_id: number;
	message?: CreateReportMessage;
	media_links?: CreateReportMediaLinks;
	start_time: string;
	end_time: string;
}
