/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { InventoryUserCreate } from "./inventoryUserCreate";

export type CreateReportInventoryUsers = InventoryUserCreate[] | null;
