/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationResponse } from "./locationResponse";
import type { RoomResponse } from "./roomResponse";
import type { TaskResponse } from "./taskResponse";
import type { RoomTaskResponse } from "./roomTaskResponse";
import type { DailyAssignmentForUserResponseAdminNote } from "./dailyAssignmentForUserResponseAdminNote";
import type { DailyAssignmentForUserResponseUserNote } from "./dailyAssignmentForUserResponseUserNote";

export interface DailyAssignmentForUserResponse {
	id: number;
	location: LocationResponse;
	rooms?: RoomResponse[];
	tasks?: TaskResponse[];
	room_tasks?: RoomTaskResponse[];
	user_id: number;
	date: string;
	admin_note?: DailyAssignmentForUserResponseAdminNote;
	user_note?: DailyAssignmentForUserResponseUserNote;
}
