/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAssignmentForUserUpdateStartTime } from "./dailyAssignmentForUserUpdateStartTime";
import type { DailyAssignmentForUserUpdateEndTime } from "./dailyAssignmentForUserUpdateEndTime";
import type { DailyAssignmentForUserUpdateStatus } from "./dailyAssignmentForUserUpdateStatus";

export interface DailyAssignmentForUserUpdate {
	start_time?: DailyAssignmentForUserUpdateStartTime;
	end_time?: DailyAssignmentForUserUpdateEndTime;
	status?: DailyAssignmentForUserUpdateStatus;
}
