/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAssignmentForUserWithHintsResponseGroupUuid } from "./dailyAssignmentForUserWithHintsResponseGroupUuid";
import type { LocationResponse } from "./locationResponse";
import type { RoomResponse } from "./roomResponse";
import type { TaskResponse } from "./taskResponse";
import type { RoomTaskResponse } from "./roomTaskResponse";
import type { AssignmentStatus } from "./assignmentStatus";
import type { DailyAssignmentForUserWithHintsResponseAdminNote } from "./dailyAssignmentForUserWithHintsResponseAdminNote";
import type { DailyAssignmentForUserWithHintsResponseUserNote } from "./dailyAssignmentForUserWithHintsResponseUserNote";
import type { DailyAssignmentForUserWithHintsResponseStartTime } from "./dailyAssignmentForUserWithHintsResponseStartTime";
import type { DailyAssignmentForUserWithHintsResponseEndTime } from "./dailyAssignmentForUserWithHintsResponseEndTime";
import type { DailyAssignmentForUserWithHintsResponseAssignedTasks } from "./dailyAssignmentForUserWithHintsResponseAssignedTasks";
import type { DailyAssignmentForUserWithHintsResponseDurationSeconds } from "./dailyAssignmentForUserWithHintsResponseDurationSeconds";
import type { DailyAssignmentForUserWithHintsResponseDurationMinutes } from "./dailyAssignmentForUserWithHintsResponseDurationMinutes";
import type { DailyAssignmentForUserWithHintsResponseDurationHours } from "./dailyAssignmentForUserWithHintsResponseDurationHours";

export interface DailyAssignmentForUserWithHintsResponse {
	id: number;
	group_uuid?: DailyAssignmentForUserWithHintsResponseGroupUuid;
	location: LocationResponse;
	rooms?: RoomResponse[];
	tasks?: TaskResponse[];
	room_tasks?: RoomTaskResponse[];
	user_id: number;
	date: string;
	status: AssignmentStatus;
	admin_note?: DailyAssignmentForUserWithHintsResponseAdminNote;
	user_note?: DailyAssignmentForUserWithHintsResponseUserNote;
	start_time?: DailyAssignmentForUserWithHintsResponseStartTime;
	end_time?: DailyAssignmentForUserWithHintsResponseEndTime;
	assigned_tasks?: DailyAssignmentForUserWithHintsResponseAssignedTasks;
	/** Вычисляет длительность в секундах */
	readonly duration_seconds: DailyAssignmentForUserWithHintsResponseDurationSeconds;
	/** Возвращает длительность в минутах */
	readonly duration_minutes: DailyAssignmentForUserWithHintsResponseDurationMinutes;
	/** Возвращает длительность в часах */
	readonly duration_hours: DailyAssignmentForUserWithHintsResponseDurationHours;
}
