/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationResponse } from "./locationResponse";
import type { RoomResponse } from "./roomResponse";
import type { TaskResponse } from "./taskResponse";
import type { RoomTaskResponse } from "./roomTaskResponse";
import type { AssignmentStatus } from "./assignmentStatus";
import type { DailyAssignmentForUserResponseAdminNote } from "./dailyAssignmentForUserResponseAdminNote";
import type { DailyAssignmentForUserResponseUserNote } from "./dailyAssignmentForUserResponseUserNote";
import type { DailyAssignmentForUserResponseStartTime } from "./dailyAssignmentForUserResponseStartTime";
import type { DailyAssignmentForUserResponseEndTime } from "./dailyAssignmentForUserResponseEndTime";
import type { DailyAssignmentForUserResponseDurationSeconds } from "./dailyAssignmentForUserResponseDurationSeconds";
import type { DailyAssignmentForUserResponseDurationMinutes } from "./dailyAssignmentForUserResponseDurationMinutes";
import type { DailyAssignmentForUserResponseDurationHours } from "./dailyAssignmentForUserResponseDurationHours";

export interface DailyAssignmentForUserResponse {
	id: number;
	location: LocationResponse;
	rooms?: RoomResponse[];
	tasks?: TaskResponse[];
	room_tasks?: RoomTaskResponse[];
	user_id: number;
	date: string;
	status: AssignmentStatus;
	admin_note?: DailyAssignmentForUserResponseAdminNote;
	user_note?: DailyAssignmentForUserResponseUserNote;
	start_time?: DailyAssignmentForUserResponseStartTime;
	end_time?: DailyAssignmentForUserResponseEndTime;
	/** Вычисляет длительность в секундах */
	readonly duration_seconds: DailyAssignmentForUserResponseDurationSeconds;
	/** Возвращает длительность в минутах */
	readonly duration_minutes: DailyAssignmentForUserResponseDurationMinutes;
	/** Возвращает длительность в часах */
	readonly duration_hours: DailyAssignmentForUserResponseDurationHours;
}
