/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskWithHintsResponse } from "./taskWithHintsResponse";
import type { RoomResponse } from "./roomResponse";
import type { DailyExtraTaskWithHintsResponseCompleted } from "./dailyExtraTaskWithHintsResponseCompleted";

export interface DailyExtraTaskWithHintsResponse {
	id: number;
	task: TaskWithHintsResponse;
	room: RoomResponse;
	completed?: DailyExtraTaskWithHintsResponseCompleted;
}
