/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */

export type GetDailyAssignmentsAndReportsParams = {
	start_date?: string | null;
	end_date?: string | null;
	dates?: string[] | null;
};
