/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { InventoryUserCreateEnding } from "./inventoryUserCreateEnding";

export interface InventoryUserCreate {
	inventory_id: number;
	user_id: number;
	ending?: InventoryUserCreateEnding;
}
