/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */

export interface RoomTaskResponse {
	room_id: number;
	task_id: number;
	id: number;
	times_since_done: number;
}
