/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskWithHintsResponseDescription } from "./taskWithHintsResponseDescription";
import type { HintsResponse } from "./hintsResponse";

export interface TaskWithHintsResponse {
	title: string;
	description?: TaskWithHintsResponseDescription;
	frequency: number;
	id: number;
	hints: HintsResponse[];
}
