/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskResponseDescription } from "./taskResponseDescription";

export interface TaskResponse {
	title: string;
	description?: TaskResponseDescription;
	frequency: number;
	id: number;
}
