/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateReportDailyAssignmentId } from "./updateReportDailyAssignmentId";
import type { UpdateReportUserId } from "./updateReportUserId";
import type { UpdateReportMessage } from "./updateReportMessage";
import type { UpdateReportMediaLinks } from "./updateReportMediaLinks";
import type { UpdateReportStartTime } from "./updateReportStartTime";
import type { UpdateReportEndTime } from "./updateReportEndTime";

/**
 * Схема для обновления отчета
 */
export interface UpdateReport {
	daily_assignment_id?: UpdateReportDailyAssignmentId;
	user_id?: UpdateReportUserId;
	message?: UpdateReportMessage;
	media_links?: UpdateReportMediaLinks;
	start_time?: UpdateReportStartTime;
	end_time?: UpdateReportEndTime;
}
