/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Auth API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActivateUserData,
  LoginData,
  RefreshTokenData,
  TokenPair
} from './generated.schemas';




  export const getNeuerStandardAuthAPI = () => {
/**
 * @summary Login
 */
const loginAuthLoginPost = <TData = AxiosResponse<TokenPair>>(
    loginData: LoginData, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      loginData,options
    );
  }

/**
 * @summary Activate
 */
const activateAuthActivatePost = <TData = AxiosResponse<TokenPair>>(
    activateUserData: ActivateUserData, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/activate`,
      activateUserData,options
    );
  }

/**
 * @summary Refresh Tokens
 */
const refreshTokensAuthRefreshTokensPost = <TData = AxiosResponse<TokenPair>>(
    refreshTokenData: RefreshTokenData, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/refresh_tokens`,
      refreshTokenData,options
    );
  }

return {loginAuthLoginPost,activateAuthActivatePost,refreshTokensAuthRefreshTokensPost}};
export type LoginAuthLoginPostResult = AxiosResponse<TokenPair>
export type ActivateAuthActivatePostResult = AxiosResponse<TokenPair>
export type RefreshTokensAuthRefreshTokensPostResult = AxiosResponse<TokenPair>
