/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Auth API
 * OpenAPI spec version: 0.1.0
 */
export type ActivateUserDataFullName = string | null;

export interface ActivateUserData {
  nickname: string;
  password: string;
  full_name?: ActivateUserDataFullName;
  token: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginData {
  nickname: string;
  password: string;
}

export interface RefreshTokenData {
  refresh_token: string;
}

export interface TokenPair {
  access_token: string;
  refresh_token: string;
  token_type: 'bearer';
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

