/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Auth API
 * OpenAPI spec version: 0.1.0
 */
import type { ActivateUserDataFullName } from "./activateUserDataFullName";

export interface ActivateUserData {
	nickname: string;
	password: string;
	full_name?: ActivateUserDataFullName;
	token: string;
}
