/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Auth API
 * OpenAPI spec version: 0.1.0
 */

export interface TokenPair {
	access_token: string;
	refresh_token: string;
	token_type: "bearer";
}
