/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
	DailyAssignmentCreate,
	DailyAssignmentResponse,
	DailyAssignmentUpdate,
	DeleteDailyAssignmentParams,
	EditDailyAssignmentParams,
	GetDailyAssignmentsParams,
	HTTPValidationError,
	SuccessResponse,
} from ".././schemas";

import { getAxios } from "../../instance";
import type { ErrorType } from "../../instance";

/**
 * @summary Get Daily Assignments
 */
export const getDailyAssignments = (params?: GetDailyAssignmentsParams, signal?: AbortSignal) => {
	return getAxios<DailyAssignmentResponse[]>({
		url: `/admin/daily-assignments/`,
		method: "GET",
		params,
		signal,
	});
};

export const getGetDailyAssignmentsQueryKey = (params?: GetDailyAssignmentsParams) => {
	return [`/admin/daily-assignments/`, ...(params ? [params] : [])] as const;
};

export const getGetDailyAssignmentsQueryOptions = <
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDailyAssignmentsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyAssignments>>> = ({ signal }) =>
		getDailyAssignments(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDailyAssignments>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDailyAssignmentsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDailyAssignments>>
>;
export type GetDailyAssignmentsQueryError = ErrorType<HTTPValidationError>;

export function useGetDailyAssignments<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetDailyAssignmentsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDailyAssignments>>,
					TError,
					Awaited<ReturnType<typeof getDailyAssignments>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignments<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDailyAssignments>>,
					TError,
					Awaited<ReturnType<typeof getDailyAssignments>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignments<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Daily Assignments
 */

export function useGetDailyAssignments<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetDailyAssignmentsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetDailyAssignmentsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDailyAssignmentsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyAssignments>>> = ({ signal }) =>
		getDailyAssignments(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDailyAssignments>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDailyAssignmentsSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDailyAssignments>>
>;
export type GetDailyAssignmentsSuspenseQueryError = ErrorType<HTTPValidationError>;

export function useGetDailyAssignmentsSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetDailyAssignmentsParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignmentsSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignmentsSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Daily Assignments
 */

export function useGetDailyAssignmentsSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignments>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetDailyAssignmentsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignments>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetDailyAssignmentsSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Create Daily Assignment
 */
export const createDailyAssignment = (
	dailyAssignmentCreate: DailyAssignmentCreate,
	signal?: AbortSignal
) => {
	return getAxios<DailyAssignmentResponse>({
		url: `/admin/daily-assignments/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: dailyAssignmentCreate,
		signal,
	});
};

export const getCreateDailyAssignmentMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createDailyAssignment>>,
		TError,
		{ data: DailyAssignmentCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createDailyAssignment>>,
	TError,
	{ data: DailyAssignmentCreate },
	TContext
> => {
	const mutationKey = ["createDailyAssignment"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createDailyAssignment>>,
		{ data: DailyAssignmentCreate }
	> = props => {
		const { data } = props ?? {};

		return createDailyAssignment(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateDailyAssignmentMutationResult = NonNullable<
	Awaited<ReturnType<typeof createDailyAssignment>>
>;
export type CreateDailyAssignmentMutationBody = DailyAssignmentCreate;
export type CreateDailyAssignmentMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create Daily Assignment
 */
export const useCreateDailyAssignment = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createDailyAssignment>>,
			TError,
			{ data: DailyAssignmentCreate },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createDailyAssignment>>,
	TError,
	{ data: DailyAssignmentCreate },
	TContext
> => {
	const mutationOptions = getCreateDailyAssignmentMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Edit Daily Assignment
 */
export const editDailyAssignment = (
	dailyAssignmentUpdate: DailyAssignmentUpdate,
	params: EditDailyAssignmentParams
) => {
	return getAxios<DailyAssignmentResponse>({
		url: `/admin/daily-assignments/`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: dailyAssignmentUpdate,
		params,
	});
};

export const getEditDailyAssignmentMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editDailyAssignment>>,
		TError,
		{ data: DailyAssignmentUpdate; params: EditDailyAssignmentParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editDailyAssignment>>,
	TError,
	{ data: DailyAssignmentUpdate; params: EditDailyAssignmentParams },
	TContext
> => {
	const mutationKey = ["editDailyAssignment"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editDailyAssignment>>,
		{ data: DailyAssignmentUpdate; params: EditDailyAssignmentParams }
	> = props => {
		const { data, params } = props ?? {};

		return editDailyAssignment(data, params);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditDailyAssignmentMutationResult = NonNullable<
	Awaited<ReturnType<typeof editDailyAssignment>>
>;
export type EditDailyAssignmentMutationBody = DailyAssignmentUpdate;
export type EditDailyAssignmentMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Edit Daily Assignment
 */
export const useEditDailyAssignment = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editDailyAssignment>>,
			TError,
			{ data: DailyAssignmentUpdate; params: EditDailyAssignmentParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof editDailyAssignment>>,
	TError,
	{ data: DailyAssignmentUpdate; params: EditDailyAssignmentParams },
	TContext
> => {
	const mutationOptions = getEditDailyAssignmentMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete Daily Assignment
 */
export const deleteDailyAssignment = (params: DeleteDailyAssignmentParams) => {
	return getAxios<SuccessResponse>({
		url: `/admin/daily-assignments/`,
		method: "DELETE",
		params,
	});
};

export const getDeleteDailyAssignmentMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteDailyAssignment>>,
		TError,
		{ params: DeleteDailyAssignmentParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteDailyAssignment>>,
	TError,
	{ params: DeleteDailyAssignmentParams },
	TContext
> => {
	const mutationKey = ["deleteDailyAssignment"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteDailyAssignment>>,
		{ params: DeleteDailyAssignmentParams }
	> = props => {
		const { params } = props ?? {};

		return deleteDailyAssignment(params);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteDailyAssignmentMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteDailyAssignment>>
>;

export type DeleteDailyAssignmentMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Delete Daily Assignment
 */
export const useDeleteDailyAssignment = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteDailyAssignment>>,
			TError,
			{ params: DeleteDailyAssignmentParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteDailyAssignment>>,
	TError,
	{ params: DeleteDailyAssignmentParams },
	TContext
> => {
	const mutationOptions = getDeleteDailyAssignmentMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
