/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import {
	useInfiniteQuery,
	useMutation,
	useQuery,
	useSuspenseInfiniteQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseInfiniteQueryOptions,
	UseSuspenseInfiniteQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
	AdminReadUser,
	DeleteUserParams,
	ForgetPasswordLink,
	ForgetPasswordLinkParams,
	GetInviteLinkParams,
	GetUsersParams,
	HTTPValidationError,
	InviteLink,
	RegisterUserData,
	SuccessResponse,
	UpdateUserParams,
	UserSchema,
	UserUpdateData,
} from ".././schemas";

import { getAxios } from "../../instance";
import type { ErrorType } from "../../instance";

/**
 * @summary Get Users
 */
export const getUsers = (params?: GetUsersParams, signal?: AbortSignal) => {
	return getAxios<AdminReadUser[]>({ url: `/admin/users/`, method: "GET", params, signal });
};

export const getGetUsersQueryKey = (params?: GetUsersParams) => {
	return [`/admin/users/`, ...(params ? [params] : [])] as const;
};

export const getGetUsersInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsers>>,
		QueryKey,
		GetUsersParams["offset"]
	> = ({ signal, pageParam }) =>
		getUsers({ ...params, offset: pageParam || params?.["offset"] }, signal);

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getUsers>>,
		QueryKey,
		GetUsersParams["offset"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;
export type GetUsersInfiniteQueryError = ErrorType<HTTPValidationError>;

export function useGetUsersInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetUsersParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Users
 */

export function useGetUsersInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetUsersInfiniteQueryOptions(params, options);

	const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) =>
		getUsers(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;
export type GetUsersQueryError = ErrorType<HTTPValidationError>;

export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetUsersParams,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Users
 */

export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetUsersQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUsersSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) =>
		getUsers(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;
export type GetUsersSuspenseQueryError = ErrorType<HTTPValidationError>;

export function useGetUsersSuspense<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetUsersParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersSuspense<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersSuspense<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Users
 */

export function useGetUsersSuspense<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetUsersSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUsersSuspenseInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsers>>,
		QueryKey,
		GetUsersParams["offset"]
	> = ({ signal, pageParam }) =>
		getUsers({ ...params, offset: pageParam || params?.["offset"] }, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getUsers>>,
		QueryKey,
		GetUsersParams["offset"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;
export type GetUsersSuspenseInfiniteQueryError = ErrorType<HTTPValidationError>;

export function useGetUsersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetUsersParams,
	options: {
		query: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Users
 */

export function useGetUsersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsers>>, GetUsersParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetUsersSuspenseInfiniteQueryOptions(params, options);

	const query = useSuspenseInfiniteQuery(
		queryOptions,
		queryClient
	) as UseSuspenseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Create User
 */
export const createUser = (registerUserData: RegisterUserData, signal?: AbortSignal) => {
	return getAxios<InviteLink>({
		url: `/admin/users/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: registerUserData,
		signal,
	});
};

export const getCreateUserMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createUser>>,
		TError,
		{ data: RegisterUserData },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createUser>>,
	TError,
	{ data: RegisterUserData },
	TContext
> => {
	const mutationKey = ["createUser"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createUser>>,
		{ data: RegisterUserData }
	> = props => {
		const { data } = props ?? {};

		return createUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>;
export type CreateUserMutationBody = RegisterUserData;
export type CreateUserMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create User
 */
export const useCreateUser = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createUser>>,
			TError,
			{ data: RegisterUserData },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createUser>>,
	TError,
	{ data: RegisterUserData },
	TContext
> => {
	const mutationOptions = getCreateUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update User
 */
export const updateUser = (userUpdateData: UserUpdateData, params: UpdateUserParams) => {
	return getAxios<UserSchema>({
		url: `/admin/users/`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: userUpdateData,
		params,
	});
};

export const getUpdateUserMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateUser>>,
		TError,
		{ data: UserUpdateData; params: UpdateUserParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateUser>>,
	TError,
	{ data: UserUpdateData; params: UpdateUserParams },
	TContext
> => {
	const mutationKey = ["updateUser"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateUser>>,
		{ data: UserUpdateData; params: UpdateUserParams }
	> = props => {
		const { data, params } = props ?? {};

		return updateUser(data, params);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type UpdateUserMutationBody = UserUpdateData;
export type UpdateUserMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Update User
 */
export const useUpdateUser = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateUser>>,
			TError,
			{ data: UserUpdateData; params: UpdateUserParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof updateUser>>,
	TError,
	{ data: UserUpdateData; params: UpdateUserParams },
	TContext
> => {
	const mutationOptions = getUpdateUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete User
 */
export const deleteUser = (params: DeleteUserParams) => {
	return getAxios<SuccessResponse>({ url: `/admin/users/`, method: "DELETE", params });
};

export const getDeleteUserMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUser>>,
		TError,
		{ params: DeleteUserParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ params: DeleteUserParams },
	TContext
> => {
	const mutationKey = ["deleteUser"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUser>>,
		{ params: DeleteUserParams }
	> = props => {
		const { params } = props ?? {};

		return deleteUser(params);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;

export type DeleteUserMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Delete User
 */
export const useDeleteUser = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUser>>,
			TError,
			{ params: DeleteUserParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ params: DeleteUserParams },
	TContext
> => {
	const mutationOptions = getDeleteUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get User By Id
 */
export const getUserById = (userId: number | undefined | null, signal?: AbortSignal) => {
	return getAxios<AdminReadUser>({ url: `/admin/users/${userId}`, method: "GET", signal });
};

export const getGetUserByIdQueryKey = (userId: number | undefined | null) => {
	return [`/admin/users/${userId}`] as const;
};

export const getGetUserByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(userId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) =>
		getUserById(userId, signal);

	return { queryKey, queryFn, enabled: !!userId, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getUserById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>;
export type GetUserByIdQueryError = ErrorType<HTTPValidationError>;

export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserById>>,
					TError,
					Awaited<ReturnType<typeof getUserById>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserById>>,
					TError,
					Awaited<ReturnType<typeof getUserById>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get User By Id
 */

export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetUserByIdQueryOptions(userId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUserByIdSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(userId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) =>
		getUserById(userId, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getUserById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>;
export type GetUserByIdSuspenseQueryError = ErrorType<HTTPValidationError>;

export function useGetUserByIdSuspense<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserByIdSuspense<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserByIdSuspense<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get User By Id
 */

export function useGetUserByIdSuspense<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<HTTPValidationError>,
>(
	userId: number | undefined | null,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetUserByIdSuspenseQueryOptions(userId, options);

	const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Forget Password Link
 */
export const forgetPasswordLink = (params: ForgetPasswordLinkParams, signal?: AbortSignal) => {
	return getAxios<ForgetPasswordLink>({
		url: `/admin/users/change-password`,
		method: "POST",
		params,
		signal,
	});
};

export const getForgetPasswordLinkMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof forgetPasswordLink>>,
		TError,
		{ params: ForgetPasswordLinkParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof forgetPasswordLink>>,
	TError,
	{ params: ForgetPasswordLinkParams },
	TContext
> => {
	const mutationKey = ["forgetPasswordLink"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof forgetPasswordLink>>,
		{ params: ForgetPasswordLinkParams }
	> = props => {
		const { params } = props ?? {};

		return forgetPasswordLink(params);
	};

	return { mutationFn, ...mutationOptions };
};

export type ForgetPasswordLinkMutationResult = NonNullable<
	Awaited<ReturnType<typeof forgetPasswordLink>>
>;

export type ForgetPasswordLinkMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Forget Password Link
 */
export const useForgetPasswordLink = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof forgetPasswordLink>>,
			TError,
			{ params: ForgetPasswordLinkParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof forgetPasswordLink>>,
	TError,
	{ params: ForgetPasswordLinkParams },
	TContext
> => {
	const mutationOptions = getForgetPasswordLinkMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get Invite Link
 */
export const getInviteLink = (params: GetInviteLinkParams, signal?: AbortSignal) => {
	return getAxios<InviteLink>({
		url: `/admin/users/get-invite-link`,
		method: "POST",
		params,
		signal,
	});
};

export const getGetInviteLinkMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getInviteLink>>,
		TError,
		{ params: GetInviteLinkParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getInviteLink>>,
	TError,
	{ params: GetInviteLinkParams },
	TContext
> => {
	const mutationKey = ["getInviteLink"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getInviteLink>>,
		{ params: GetInviteLinkParams }
	> = props => {
		const { params } = props ?? {};

		return getInviteLink(params);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetInviteLinkMutationResult = NonNullable<Awaited<ReturnType<typeof getInviteLink>>>;

export type GetInviteLinkMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Get Invite Link
 */
export const useGetInviteLink = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getInviteLink>>,
			TError,
			{ params: GetInviteLinkParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof getInviteLink>>,
	TError,
	{ params: GetInviteLinkParams },
	TContext
> => {
	const mutationOptions = getGetInviteLinkMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
