/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type { DailyAssignmentForUserResponse } from ".././schemas";

import { getAxios } from "../../instance";
import type { ErrorType } from "../../instance";

/**
 * @summary Get Daily Assignment
 */
export const getDailyAssignment = (signal?: AbortSignal) => {
	return getAxios<DailyAssignmentForUserResponse[]>({
		url: `/client/assignments/daily-assignment`,
		method: "GET",
		signal,
	});
};

export const getGetDailyAssignmentQueryKey = () => {
	return [`/client/assignments/daily-assignment`] as const;
};

export const getGetDailyAssignmentQueryOptions = <
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDailyAssignmentQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyAssignment>>> = ({ signal }) =>
		getDailyAssignment(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDailyAssignment>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDailyAssignmentQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDailyAssignment>>
>;
export type GetDailyAssignmentQueryError = ErrorType<unknown>;

export function useGetDailyAssignment<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDailyAssignment>>,
					TError,
					Awaited<ReturnType<typeof getDailyAssignment>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignment<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDailyAssignment>>,
					TError,
					Awaited<ReturnType<typeof getDailyAssignment>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignment<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Daily Assignment
 */

export function useGetDailyAssignment<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetDailyAssignmentQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetDailyAssignmentSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDailyAssignmentQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyAssignment>>> = ({ signal }) =>
		getDailyAssignment(signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDailyAssignment>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDailyAssignmentSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDailyAssignment>>
>;
export type GetDailyAssignmentSuspenseQueryError = ErrorType<unknown>;

export function useGetDailyAssignmentSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignmentSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyAssignmentSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Daily Assignment
 */

export function useGetDailyAssignmentSuspense<
	TData = Awaited<ReturnType<typeof getDailyAssignment>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDailyAssignment>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetDailyAssignmentSuspenseQueryOptions(options);

	const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
