/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standart Client API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
	CreateReport,
	GetReportParams,
	HTTPValidationError,
	ReportResponse,
	UpdateReport,
	UpdateReportParams,
} from ".././schemas";

import { getAxios } from "../../instance";
import type { ErrorType } from "../../instance";

/**
 * @summary Get Report
 */
export const getReport = (params: GetReportParams, signal?: AbortSignal) => {
	return getAxios<unknown>({ url: `/client/reports/`, method: "GET", params, signal });
};

export const getGetReportQueryKey = (params: GetReportParams) => {
	return [`/client/reports/`, ...(params ? [params] : [])] as const;
};

export const getGetReportQueryOptions = <
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReportQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getReport>>> = ({ signal }) =>
		getReport(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getReport>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportQueryResult = NonNullable<Awaited<ReturnType<typeof getReport>>>;
export type GetReportQueryError = ErrorType<HTTPValidationError>;

export function useGetReport<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReport>>,
					TError,
					Awaited<ReturnType<typeof getReport>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReport<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReport>>,
					TError,
					Awaited<ReturnType<typeof getReport>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReport<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Report
 */

export function useGetReport<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReportQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetReportSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReportQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getReport>>> = ({ signal }) =>
		getReport(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getReport>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getReport>>>;
export type GetReportSuspenseQueryError = ErrorType<HTTPValidationError>;

export function useGetReportSuspense<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportSuspense<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportSuspense<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Report
 */

export function useGetReportSuspense<
	TData = Awaited<ReturnType<typeof getReport>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: GetReportParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReportSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Create Report
 */
export const createReport = (createReport: CreateReport, signal?: AbortSignal) => {
	return getAxios<ReportResponse>({
		url: `/client/reports/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createReport,
		signal,
	});
};

export const getCreateReportMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createReport>>,
		TError,
		{ data: CreateReport },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createReport>>,
	TError,
	{ data: CreateReport },
	TContext
> => {
	const mutationKey = ["createReport"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createReport>>,
		{ data: CreateReport }
	> = props => {
		const { data } = props ?? {};

		return createReport(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateReportMutationResult = NonNullable<Awaited<ReturnType<typeof createReport>>>;
export type CreateReportMutationBody = CreateReport;
export type CreateReportMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create Report
 */
export const useCreateReport = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createReport>>,
			TError,
			{ data: CreateReport },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createReport>>,
	TError,
	{ data: CreateReport },
	TContext
> => {
	const mutationOptions = getCreateReportMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update Report
 */
export const updateReport = (updateReport: UpdateReport, params: UpdateReportParams) => {
	return getAxios<ReportResponse>({
		url: `/client/reports/`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updateReport,
		params,
	});
};

export const getUpdateReportMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateReport>>,
		TError,
		{ data: UpdateReport; params: UpdateReportParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateReport>>,
	TError,
	{ data: UpdateReport; params: UpdateReportParams },
	TContext
> => {
	const mutationKey = ["updateReport"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateReport>>,
		{ data: UpdateReport; params: UpdateReportParams }
	> = props => {
		const { data, params } = props ?? {};

		return updateReport(data, params);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateReport>>>;
export type UpdateReportMutationBody = UpdateReport;
export type UpdateReportMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Update Report
 */
export const useUpdateReport = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateReport>>,
			TError,
			{ data: UpdateReport; params: UpdateReportParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof updateReport>>,
	TError,
	{ data: UpdateReport; params: UpdateReportParams },
	TContext
> => {
	const mutationOptions = getUpdateReportMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
