/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Users API
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateUserDataNickname } from "./updateUserDataNickname";
import type { UpdateUserDataFullName } from "./updateUserDataFullName";

export interface UpdateUserData {
	nickname?: UpdateUserDataNickname;
	full_name?: UpdateUserDataFullName;
}
