/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Users API
 * OpenAPI spec version: 0.1.0
 */

export interface UserUpdatePassword {
	old_password: string;
	new_password: string;
}
