/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Users API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from "./userRole";
import type { UserStatus } from "./userStatus";
import type { UserSchemaFullName } from "./userSchemaFullName";
import type { UserSchemaAdminNote } from "./userSchemaAdminNote";

export interface UserSchema {
	id: number;
	nickname: string;
	role: UserRole;
	status: UserStatus;
	full_name: UserSchemaFullName;
	admin_note: UserSchemaAdminNote;
	created_at: string;
}
