/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseInfiniteQueryOptions,
	UseSuspenseInfiniteQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useMutation,
	useQuery,
	useSuspenseInfiniteQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";

import type {
	DeleteReportParams,
	GetReportsParams,
	HTTPValidationError,
	ReportWithAssignmentDateResponse,
	SuccessResponse,
} from ".././schemas";

import type { ErrorType } from "../../instance";
import { getAxios } from "../../instance";

/**
 * @summary Get Reports
 */
export const getReports = (params?: GetReportsParams, signal?: AbortSignal) => {
	return getAxios<ReportWithAssignmentDateResponse[]>({
		url: `/admin/reports/`,
		method: "GET",
		params,
		signal,
	});
};

export const getGetReportsQueryKey = (params?: GetReportsParams) => {
	return [`/admin/reports/`, ...(params ? [params] : [])] as const;
};

export const getGetReportsInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReportsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getReports>>,
		QueryKey,
		GetReportsParams["offset"]
	> = ({ signal, pageParam }) =>
		getReports({ ...params, offset: pageParam || params?.["offset"] }, signal);

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getReports>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getReports>>,
		QueryKey,
		GetReportsParams["offset"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getReports>>>;
export type GetReportsInfiniteQueryError = ErrorType<HTTPValidationError>;

export function useGetReportsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetReportsParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReports>>,
					TError,
					Awaited<ReturnType<typeof getReports>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReports>>,
					TError,
					Awaited<ReturnType<typeof getReports>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Reports
 */

export function useGetReportsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReportsInfiniteQueryOptions(params, options);

	const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetReportsQueryOptions = <
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReportsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getReports>>> = ({ signal }) =>
		getReports(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getReports>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getReports>>>;
export type GetReportsQueryError = ErrorType<HTTPValidationError>;

export function useGetReports<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetReportsParams,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReports>>,
					TError,
					Awaited<ReturnType<typeof getReports>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReports<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReports>>,
					TError,
					Awaited<ReturnType<typeof getReports>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReports<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Reports
 */

export function useGetReports<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReportsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetReportsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReportsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getReports>>> = ({ signal }) =>
		getReports(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getReports>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getReports>>>;
export type GetReportsSuspenseQueryError = ErrorType<HTTPValidationError>;

export function useGetReportsSuspense<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetReportsParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportsSuspense<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportsSuspense<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Reports
 */

export function useGetReportsSuspense<
	TData = Awaited<ReturnType<typeof getReports>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReportsSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetReportsSuspenseInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReportsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getReports>>,
		QueryKey,
		GetReportsParams["offset"]
	> = ({ signal, pageParam }) =>
		getReports({ ...params, offset: pageParam || params?.["offset"] }, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getReports>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getReports>>,
		QueryKey,
		GetReportsParams["offset"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportsSuspenseInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getReports>>
>;
export type GetReportsSuspenseInfiniteQueryError = ErrorType<HTTPValidationError>;

export function useGetReportsSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | GetReportsParams,
	options: {
		query: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportsSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReportsSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Reports
 */

export function useGetReportsSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getReports>>, GetReportsParams["offset"]>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: GetReportsParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getReports>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getReports>>,
				QueryKey,
				GetReportsParams["offset"]
			>
		>;
	},
	queryClient?: QueryClient
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReportsSuspenseInfiniteQueryOptions(params, options);

	const query = useSuspenseInfiniteQuery(
		queryOptions,
		queryClient
	) as UseSuspenseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Delete Report
 */
export const deleteReport = (params: DeleteReportParams) => {
	return getAxios<SuccessResponse>({ url: `/admin/reports/`, method: "DELETE", params });
};

export const getDeleteReportMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteReport>>,
		TError,
		{ params: DeleteReportParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteReport>>,
	TError,
	{ params: DeleteReportParams },
	TContext
> => {
	const mutationKey = ["deleteReport"];
	const { mutation: mutationOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteReport>>,
		{ params: DeleteReportParams }
	> = props => {
		const { params } = props ?? {};

		return deleteReport(params);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteReportMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReport>>>;

export type DeleteReportMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Delete Report
 */
export const useDeleteReport = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteReport>>,
			TError,
			{ params: DeleteReportParams },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteReport>>,
	TError,
	{ params: DeleteReportParams },
	TContext
> => {
	const mutationOptions = getDeleteReportMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
