/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  RootGet200
} from './generated.schemas';




  export const getNeuerStandardAPI = () => {
/**
 * @summary Root
 */
const rootGet = <TData = AxiosResponse<RootGet200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

/**
 * @summary Health
 */
const healthHealthGet = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/health`,options
    );
  }

return {rootGet,healthHealthGet}};
export type RootGetResult = AxiosResponse<RootGet200>
export type HealthHealthGetResult = AxiosResponse<string>
