/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { AdminReadUserNickname } from "./adminReadUserNickname";
import type { UserRole } from "./userRole";
import type { UserStatus } from "./userStatus";
import type { AdminReadUserFullName } from "./adminReadUserFullName";
import type { AdminReadUserAdminNote } from "./adminReadUserAdminNote";

export interface AdminReadUser {
	id: number;
	nickname: AdminReadUserNickname;
	role: UserRole;
	status: UserStatus;
	full_name: AdminReadUserFullName;
	admin_note: AdminReadUserAdminNote;
	created_at: string;
}
