/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyExtraTaskUpdateDailyAssignmentId } from "./dailyExtraTaskUpdateDailyAssignmentId";
import type { DailyExtraTaskUpdateRoomId } from "./dailyExtraTaskUpdateRoomId";
import type { DailyExtraTaskUpdateTaskId } from "./dailyExtraTaskUpdateTaskId";

export interface DailyExtraTaskUpdate {
	daily_assignment_id?: DailyExtraTaskUpdateDailyAssignmentId;
	room_id?: DailyExtraTaskUpdateRoomId;
	task_id?: DailyExtraTaskUpdateTaskId;
}
