/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAssignmentWithLocationAndUserResponseGroupUuid } from "./dailyAssignmentWithLocationAndUserResponseGroupUuid";
import type { DailyAssignmentWithLocationAndUserResponseAdminNote } from "./dailyAssignmentWithLocationAndUserResponseAdminNote";
import type { DailyAssignmentWithLocationAndUserResponseUserNote } from "./dailyAssignmentWithLocationAndUserResponseUserNote";
import type { DailyAssignmentWithLocationAndUserResponseStartTime } from "./dailyAssignmentWithLocationAndUserResponseStartTime";
import type { DailyAssignmentWithLocationAndUserResponseEndTime } from "./dailyAssignmentWithLocationAndUserResponseEndTime";
import type { LocationResponse } from "./locationResponse";
import type { AdminReadUser } from "./adminReadUser";

export interface DailyAssignmentWithLocationAndUserResponse {
	id: number;
	group_uuid?: DailyAssignmentWithLocationAndUserResponseGroupUuid;
	location_id: number;
	user_id: number;
	date: string;
	admin_note?: DailyAssignmentWithLocationAndUserResponseAdminNote;
	user_note?: DailyAssignmentWithLocationAndUserResponseUserNote;
	start_time?: DailyAssignmentWithLocationAndUserResponseStartTime;
	end_time?: DailyAssignmentWithLocationAndUserResponseEndTime;
	location: LocationResponse;
	user: AdminReadUser;
}
