/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAssignmentUpdateLocationId } from "./dailyAssignmentUpdateLocationId";
import type { DailyAssignmentUpdateUserId } from "./dailyAssignmentUpdateUserId";
import type { DailyAssignmentUpdateDate } from "./dailyAssignmentUpdateDate";
import type { DailyAssignmentUpdateAdminNote } from "./dailyAssignmentUpdateAdminNote";
import type { DailyAssignmentUpdateUserNote } from "./dailyAssignmentUpdateUserNote";

export interface DailyAssignmentUpdate {
	location_id?: DailyAssignmentUpdateLocationId;
	user_id?: DailyAssignmentUpdateUserId;
	date?: DailyAssignmentUpdateDate;
	admin_note?: DailyAssignmentUpdateAdminNote;
	user_note?: DailyAssignmentUpdateUserNote;
}
