/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */

export type GetRoomTasksParams = {
	offset?: number | null;
	limit?: number | null;
	search?: string | null;
	order_by?: string | null;
	direction?: string | null;
};
