/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from "./userRole";
import type { UserStatus } from "./userStatus";
import type { UserFields } from "./userFields";
import type { SortDirection } from "./sortDirection";

export type GetUsersParams = {
	role?: UserRole | null;
	status?: UserStatus | null;
	nickname?: string | null;
	search?: string | null;
	offset?: number | null;
	limit?: number | null;
	order_by?: UserFields | null;
	direction?: SortDirection | null;
};
