/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { HintsResponseText } from "./hintsResponseText";
import type { HintsResponseMediaLinks } from "./hintsResponseMediaLinks";

export interface HintsResponse {
	title: string;
	text?: HintsResponseText;
	media_links?: HintsResponseMediaLinks;
	task_id: number;
	id: number;
}
