/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { HintsCreateText } from "./hintsCreateText";
import type { HintsCreateMediaLinks } from "./hintsCreateMediaLinks";

export interface HintsCreate {
	title: string;
	text?: HintsCreateText;
	media_links?: HintsCreateMediaLinks;
	task_id: number;
}
