/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { InventoryUpdateTitle } from "./inventoryUpdateTitle";
import type { InventoryUpdateDescription } from "./inventoryUpdateDescription";
import type { InventoryUpdateMediaLinks } from "./inventoryUpdateMediaLinks";

export interface InventoryUpdate {
	title?: InventoryUpdateTitle;
	description?: InventoryUpdateDescription;
	media_links?: InventoryUpdateMediaLinks;
	task_id: number;
}
