/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { InventoryCreateTitle } from "./inventoryCreateTitle";
import type { InventoryCreateDescription } from "./inventoryCreateDescription";
import type { InventoryCreateMediaLinks } from "./inventoryCreateMediaLinks";

export interface InventoryCreate {
	title?: InventoryCreateTitle;
	description?: InventoryCreateDescription;
	media_links?: InventoryCreateMediaLinks;
	task_id: number;
}
