/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { InventoryUserUpdateInventoryId } from "./inventoryUserUpdateInventoryId";
import type { InventoryUserUpdateUserId } from "./inventoryUserUpdateUserId";
import type { InventoryUserUpdateReportId } from "./inventoryUserUpdateReportId";
import type { InventoryUserUpdateEnding } from "./inventoryUserUpdateEnding";

export interface InventoryUserUpdate {
	inventory_id?: InventoryUserUpdateInventoryId;
	user_id?: InventoryUserUpdateUserId;
	report_id?: InventoryUserUpdateReportId;
	ending?: InventoryUserUpdateEnding;
}
