/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationCreateAddress } from "./locationCreateAddress";

export interface LocationCreate {
	name: string;
	address?: LocationCreateAddress;
}
