/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationUpdateName } from "./locationUpdateName";
import type { LocationUpdateAddress } from "./locationUpdateAddress";

export interface LocationUpdate {
	name?: LocationUpdateName;
	address?: LocationUpdateAddress;
}
