/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportResponseMessage } from "./reportResponseMessage";
import type { ReportResponseMediaLinks } from "./reportResponseMediaLinks";
import type { ReportResponseStartTime } from "./reportResponseStartTime";
import type { ReportResponseEndTime } from "./reportResponseEndTime";
import type { AssignmentStatus } from "./assignmentStatus";
import type { ReportResponseDurationSeconds } from "./reportResponseDurationSeconds";
import type { ReportResponseDurationMinutes } from "./reportResponseDurationMinutes";
import type { ReportResponseDurationHours } from "./reportResponseDurationHours";

/**
 * Схема для ответа API
 */
export interface ReportResponse {
	daily_assignment_id: number;
	user_id: number;
	message?: ReportResponseMessage;
	media_links?: ReportResponseMediaLinks;
	start_time?: ReportResponseStartTime;
	end_time?: ReportResponseEndTime;
	status: AssignmentStatus;
	id: number;
	/** Вычисляет длительность в секундах */
	readonly duration_seconds: ReportResponseDurationSeconds;
	/** Возвращает длительность в минутах */
	readonly duration_minutes: ReportResponseDurationMinutes;
	/** Возвращает длительность в часах */
	readonly duration_hours: ReportResponseDurationHours;
}
