/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportExportResponseUserId } from "./reportExportResponseUserId";
import type { ReportExportResponseLang } from "./reportExportResponseLang";
import type { ReportStatus } from "./reportStatus";

export interface ReportExportResponse {
	export_type: string;
	start_date: string;
	end_date: string;
	timezone?: string;
	user_id?: ReportExportResponseUserId;
	lang?: ReportExportResponseLang;
	id: number;
	status: ReportStatus;
}
