/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */

export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportStatus = {
	waiting: "waiting",
	in_progress: "in_progress",
	failed: "failed",
	completed: "completed",
} as const;
