/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportExportParamsUserId } from "./reportExportParamsUserId";
import type { ReportExportParamsLang } from "./reportExportParamsLang";

export interface ReportExportParams {
	export_type: string;
	start_date: string;
	end_date: string;
	timezone?: string;
	user_id?: ReportExportParamsUserId;
	lang?: ReportExportParamsLang;
}
