/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportWithAssignmentDateResponseStartTime } from "./reportWithAssignmentDateResponseStartTime";
import type { ReportWithAssignmentDateResponseEndTime } from "./reportWithAssignmentDateResponseEndTime";
import type { ReportWithAssignmentDateResponseLocationName } from "./reportWithAssignmentDateResponseLocationName";
import type { ReportWithAssignmentDateResponseUserFullName } from "./reportWithAssignmentDateResponseUserFullName";
import type { ReportWithAssignmentDateResponseReportRooms } from "./reportWithAssignmentDateResponseReportRooms";
import type { ReportWithAssignmentDateResponseMessage } from "./reportWithAssignmentDateResponseMessage";
import type { ReportWithAssignmentDateResponseMediaLinks } from "./reportWithAssignmentDateResponseMediaLinks";
import type { AssignmentStatus } from "./assignmentStatus";
import type { ReportWithAssignmentDateResponseAssignmentDate } from "./reportWithAssignmentDateResponseAssignmentDate";
import type { ReportWithAssignmentDateResponseDurationSeconds } from "./reportWithAssignmentDateResponseDurationSeconds";
import type { ReportWithAssignmentDateResponseDurationMinutes } from "./reportWithAssignmentDateResponseDurationMinutes";
import type { ReportWithAssignmentDateResponseDurationHours } from "./reportWithAssignmentDateResponseDurationHours";

export interface ReportWithAssignmentDateResponse {
	start_time?: ReportWithAssignmentDateResponseStartTime;
	end_time?: ReportWithAssignmentDateResponseEndTime;
	id: number;
	daily_assignment_id: number;
	user_id: number;
	location_name?: ReportWithAssignmentDateResponseLocationName;
	user_full_name?: ReportWithAssignmentDateResponseUserFullName;
	report_rooms?: ReportWithAssignmentDateResponseReportRooms;
	message?: ReportWithAssignmentDateResponseMessage;
	media_links?: ReportWithAssignmentDateResponseMediaLinks;
	status: AssignmentStatus;
	assignment_date: ReportWithAssignmentDateResponseAssignmentDate;
	/** Вычисляет длительность в секундах */
	readonly duration_seconds: ReportWithAssignmentDateResponseDurationSeconds;
	/** Возвращает длительность в минутах */
	readonly duration_minutes: ReportWithAssignmentDateResponseDurationMinutes;
	/** Возвращает длительность в часах */
	readonly duration_hours: ReportWithAssignmentDateResponseDurationHours;
}
