/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { RoomStatus } from "./roomStatus";

export interface ReportRoomResponse {
	room_id: number;
	report_id: number;
	status: RoomStatus;
}
