/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Возвращает длительность в часах
 */
export type ReportWithAssignmentDateResponseDurationHours = number | null;
