/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { RoomUpdateName } from "./roomUpdateName";
import type { RoomUpdateLocationId } from "./roomUpdateLocationId";

export interface RoomUpdate {
	name?: RoomUpdateName;
	location_id?: RoomUpdateLocationId;
}
