/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { RoomTaskUpdateTimesSinceDone } from "./roomTaskUpdateTimesSinceDone";
import type { RoomTaskUpdateRoomId } from "./roomTaskUpdateRoomId";
import type { RoomTaskUpdateTaskId } from "./roomTaskUpdateTaskId";

export interface RoomTaskUpdate {
	times_since_done?: RoomTaskUpdateTimesSinceDone;
	room_id?: RoomTaskUpdateRoomId;
	task_id?: RoomTaskUpdateTaskId;
}
