/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */

export type RoomStatus = (typeof RoomStatus)[keyof typeof RoomStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomStatus = {
	not_done: "not_done",
	done: "done",
	partially_done: "partially_done",
} as const;
