/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Neuer Standard Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateDataNickname } from "./userUpdateDataNickname";
import type { UserUpdateDataPassword } from "./userUpdateDataPassword";
import type { UserUpdateDataRole } from "./userUpdateDataRole";
import type { UserUpdateDataStatus } from "./userUpdateDataStatus";
import type { UserUpdateDataFullName } from "./userUpdateDataFullName";
import type { UserUpdateDataAdminNote } from "./userUpdateDataAdminNote";

export interface UserUpdateData {
	nickname?: UserUpdateDataNickname;
	password?: UserUpdateDataPassword;
	role?: UserUpdateDataRole;
	status?: UserUpdateDataStatus;
	full_name?: UserUpdateDataFullName;
	admin_note?: UserUpdateDataAdminNote;
}
